### ISSUE TITLE
How to solve the problem "cPickle.UnpicklingError: invalid load key, 'v'."

### ISSUE THREAD

**Issue by Julinear** [arne-cl/codra-rst-parser#1]
Dear @arne-cl 
![image](https://user-images.githubusercontent.com/33052315/51219654-c6900380-196c-11e9-81ed-2788da080b3b.png)
   In file "serialize.py" which used for getting tag features, an error occurs when function "LodaData" use 
   cPickle to load the file as follows: 
![image](https://user-images.githubusercontent.com/33052315/51219200-acedbc80-196a-11e9-9d03-27ac1fa8ffaa.png)
    I try to open the file, it just shows  like this: 
![image](https://user-images.githubusercontent.com/33052315/51219416-d824db80-196b-11e9-8381-d07d793c80f6.png)
   I don't know what it means, do you have any solutions?
Best regards
Julinear

**Comment by arne-cl** [comment]
Dear @Julinear,

sorry for the late reply! I guess you have already found an answer to your question.

I should have deprecated this repo, but forgot to do so. Github has [restrictions on large files](https://git-lfs.github.com/), which makes it impossible to host CODRA here for free.
While the original CODRA source code is still available on [Shafiq Joty's old website](http://alt.qcri.org/tools/discourse-parser/), I needed to make some changes to get the parser running.
My fork (including all models / large files) is available in the [codra-rst-parser](https://sourceforge.net/projects/codra-rst-parser/) repo on sourceforge.

If you simply want to install and run the CODRA RST parser (using Docker), please use [NLPbox/codra-docker](https://github.com/NLPbox/codra-docker). For even more convenience, check out [NLPbox/codra-service](https://github.com/NLPbox/codra-service), which offers a REST API for the parser.
